# -*- coding: utf-8 -*-
"""talrop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j6n4vxZhcTSSxRe-0YDKv9yy7Udu6PM4
"""

!pip install diffusers transformers accelerate torch torchvision torchaudio ffmpeg-python

from diffusers import StableDiffusionPipeline
import torch
torch.cuda.is_available()
from PIL import Image
import ffmpeg
from IPython.display import HTML, display
from base64 import b64encode

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
pipe = pipe.to("cuda")

prompt = input("Enter subject + action: ")
style = input("Enter style (cartoon, cinematic, etc.): ")
camera_angle = input("Enter camera angle (top-down, side view, etc.): ")
duration = int(input("Enter duration in seconds (max 10): "))

full_prompt = f"{prompt}, {style}, {camera_angle}"

num_frames = max(duration * 2, 4)
frames = []

for i in range(num_frames):
    img = pipe(full_prompt, guidance_scale=7.5).images[0].resize((256,256))
    frames.append(img)

frames[0].save("output.gif", save_all=True, append_images=frames[1:], duration=500, loop=0)

(
    ffmpeg
    .input("output.gif")
    .output("output.mp4", pix_fmt="yuv420p", vf="scale=256:256")
    .overwrite_output()
    .run(quiet=True)
)

mp4 = open("output.mp4","rb").read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
display(HTML(f'<video width=256 height=256 controls><source src="{data_url}" type="video/mp4"></video>'))